pipeline {
   agent any

   stages {
      stage('Checkout') {
         steps {
            echo "test"
             //git 'https://github.com/morri421/MobGame.git'
         }
      }
      stage('Build') {
         steps {
             sh "mvn clean package"
         }
      }
   }
}